# Generated by Django 3.2.25 on 2025-08-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0043_auto_20250514_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='plus_10_count',
            field=models.IntegerField(default=0, verbose_name='Plus 10 Count'),
        ),
        migrations.AddField(
            model_name='commission',
            name='plus_count',
            field=models.IntegerField(default=0, verbose_name='Plus Count'),
        ),
        migrations.AddField(
            model_name='commission',
            name='target_Team_count',
            field=models.IntegerField(default=0, verbose_name='Target Team Count'),
        ),
        migrations.AddField(
            model_name='commission',
            name='target_count',
            field=models.IntegerField(default=0, verbose_name='Target Count'),
        ),
    ]
