# Generated by Django 3.2.25 on 2025-08-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_whatsappaccount_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set(),
        ),
    ]
