# Generated by Django 3.2.25 on 2025-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_lead_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'phone'), name='unique_project_phone'),
        ),
    ]
